<html>
   <head><title>{titulo}</title></head>
<body>
   <section>
		<article>
			<header>
				<h1>{artigo_titulo}</h1>
			</header>
			<div>{artigo_conteudo}</div>
		</article>
	</section>
	<footer>{rodape}</footer>
</body>
</html>
